[tool.poetry]
name = "repl_python3_day-1-1-exercise"
version = "0.1.0"
description = ""
authors = ["NeenuPaul <<>>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
